name: Notify dockerhub build Swow image

on: [ push ]

jobs:
  run-actions:
    if: env.DOCKER_ACTION_REPO && secrets.DOCKER_ACTION_TOKEN
    name: Notify action repo to run update action
    runs-on: ubuntu-latest
    steps:
      - name: Use Github REST API to start workflow
        run: |
          echo curl \
            -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ env.DOCKER_ACTION_REPO }}/actions/workflows/update.yml/dispatches \
            -d '{"event_type":"Update from Swow", "client_payload":{"ref":}}'