name: Notify dockerhub build Swow image

on: [ push ]

jobs:
  run-actions:
    name: Notify action repo to run update action
    runs-on: ubuntu-latest
    steps:
      - name: Check if we know which repo is action repo
        id: check
        continue-on-error: true
        run: |
          if [ x"${{ secrets.DOCKER_ACTION_TOKEN }}" = x"" ]
          then
            echo "::error::DOCKER_ACTION_TOKEN secret is not set" >&2
            exit 1
          fi
          if [ x"${{ secrets.DOCKER_ACTION_REPO }}" = x"" ]
          then
            echo "::error::DOCKER_ACTION_REPO secret is not set" >&2
            exit 1
          fi

      - name: Start update workflow run
        if: steps.check.outcome == 'success'
        run: |
          ref=${{ github.ref }}
          rev=$GITHUB_SHA
          curl \
            -X POST \
            -H "accept: application/vnd.github.v3+json" \
            -H "authorization: Bearer ${{ secrets.DOCKER_ACTION_TOKEN }}" \
            https://api.github.com/repos/${{ secrets.DOCKER_ACTION_REPO }}/actions/workflows/update.yml/dispatches \
            -d '{"event_type":"Update from Swow", "client_payload":{"ref":"'${ref##*/}'","rev":"'${rev}'"}}'