name: releases

on:
  workflow_dispatch:
    inputs:
      ref:
        description: 'Using Swow commmit'
        required: false
  push:
    tags:
    - 'v*'

jobs:
  builddlls:
    # this name is used after, change it with cautious
    name: Build dll for PHP-${{ matrix.phpver }}-${{ matrix.arch }}-${{ (matrix.ts == '0') && 'N' || '' }}TS-${{ (matrix.os == 'windows-latest') && 'VS16' || 'VC15' }}
    runs-on: "${{ matrix.os }}"
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, windows-2016]
        phpver: ["8.0","7.4","7.3"]
        arch: ["x64"]
        ts: ["0", "1"]
        exclude:
          - os: windows-latest
            phpver: "7.4"
          - os: windows-latest
            phpver: "7.3"
          - os: windows-2016
            phpver: "8.0"
      max-parallel: 6
    outputs:
      ref: ${{ steps.getref.outputs.ref }}
    env:
      deps: openssl,libcurl,zlib,libssh2,nghttp2
      tools_path: C:\tools\phpdev
      dllname: "php_swow-php${{ matrix.phpver }}-${{ matrix.arch }}-${{ (matrix.ts == '0') && 'n' || '' }}ts-${{ (matrix.os == 'windows-latest') && 'VS16' || 'VC15' }}.dll"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ (github.event.inputs && github.event.inputs.ref) || github.ref }}
      - name: Get git commit ref hash
        id: getref
        shell: powershell
        run: |
          $ref = git rev-parse HEAD 
          Write-Host "::set-output name=ref::$ref"
      - name: Prepare caches
        id: cacheprepare
        env:
          UNIX_COLOR: 1
        run: |
          . "./.github/workflows/winext/utils.ps1" -ToolName "cacheprepare" -MaxTry 3
          $os = "${{ matrix.os }}"
          if($os.Equals("windows-latest") -Or $os.Equals("windows-2019")){
            $PhpVCVer = "VS16"
          }elseif($os.Equals("windows-2016")){
            $PhpVCVer = "VC15"
          }
          function phpsdkver{
            $headers = @{
              "accept"="application/vnd.github.v3+json";
              "content-type"="application/json";
              "authorization"="Bearer ${{ secrets.GITHUB_TOKEN }}";
            }
            $info = fetchjson -Uri "https://api.github.com/repos/microsoft/php-sdk-binary-tools/git/ref/heads/master" -Headers $headers
            if(!$info){
              warn "Cannot fetch php-sdk-binary-tools info from api.github.com"
            }else{
              $ver = $info."object"."sha"
              Write-Host "::set-output name=phpsdkver::$ver"
            }
          }
          info "Using $PhpVCVer"
          $ret = 1
          phpsdkver
          ./.github/workflows/winext/getphp.ps1 `
            -PhpVer ${{ matrix.phpver }} `
            -PhpArch ${{ matrix.arch }} `
            -PhpVCVer $PhpVCVer `
            -PhpTs ${{ matrix.ts }} `
            -DryRun 1 &&
          ./.github/workflows/winext/devpack.ps1 `
            -PhpVer ${{ matrix.phpver }} `
            -PhpArch ${{ matrix.arch }} `
            -PhpVCVer $PhpVCVer `
            -PhpTs ${{ matrix.ts }} `
            -DryRun 1 &&
          ./.github/workflows/winext/deps.ps1 `
            ${{ env.deps }} `
            -DryRun 1 &&
          ($ret = 0 | Out-Null)
          exit $ret
      - name: Cache build environments
        uses: actions/cache@v2
        with:
          # this should be ok, but there's a bug, excluding not work properly
          # see https://github.com/actions/cache/issues/494
          # see https://github.com/actions/toolkit/issues/713
          # so we must remove dll and ini before
          path: |
            ${{ env.tools_path }}
            !${{ env.tools_path }}\php\ext\php_swow.dll
            !${{ env.tools_path }}\php\php.ini
          key: buildenv-v4-${{ matrix.arch }}-${{ matrix.ts }}-${{ steps.cacheprepare.outputs.phpver }}-${{ steps.cacheprepare.outputs.devpackver }}-${{ steps.cacheprepare.outputs.downloadeddeps }}-${{ steps.cacheprepare.outputs.phpsdkver }}
      - name: Build Swow extension
        id: ext-build
        uses: ./.github/workflows/winext
        with:
          ext-path: ./ext
          tools-path: ${{ env.tools_path }}
          ext-name: swow
          deps: ${{ env.deps }}
          phpver: ${{ matrix.phpver }}
          phpts: ${{ matrix.ts }}
          phparch: ${{ matrix.arch }}
          install: "0"
          conf-args: "--enable-swow-ssl --enable-swow-curl"
      - name: Generate information about this dll
        shell: powershell
        run: |
          $fn = "${{ env.dllname }}"
          Copy-Item ext\${{ matrix.arch }}\Release${{ matrix.ts == 1 && '_TS' || '' }}\php_swow.dll $fn
          @{
            "name" = $fn;
            "size" = (Get-Item $fn).Length;
            "hash" = (Get-FileHash -Algorithm SHA256 $fn).Hash;
            "result" = "${{ steps.ext-test.outcome }}";
            "runid" = "${{ github.run_id }}";
            "jobname" = "PHP-${{ matrix.phpver }}-${{ matrix.arch }}-${{ (matrix.ts == '0') && 'N' || '' }}TS-${{ (matrix.os == 'windows-latest') && 'VS16' || 'VC15' }}";
          } | ConvertTo-Json -Compress | Out-File "${fn}.json" -Encoding ASCII # for no BOM
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: "${{ steps.getref.outputs.ref }}"
          path: |
            ${{ env.dllname }}
            ${{ env.dllname }}.json
      - name: Prepare php for test
        id: php-inst
        continue-on-error: true
        shell: powershell
        env:
          UNIX_COLOR: "1"
        run: |
          Write-Host "::group::Fetching php from windows.php.net"
          .\.github\workflows\winext\getphp.ps1 `
            -PhpVer "${{ matrix.phpver }}" `
            -PhpVCVer "${{ steps.ext-build.outputs.vcver }}" `
            -PhpTs ${{ matrix.ts }}
          $ret = $lastexitcode
          Write-Host "::endgroup::"
          if( 0 -Ne $ret ){
              exit 1
          }
          Write-Host "::group::Installing swow"
          Copy-Item ext\${{ matrix.arch }}\Release${{ matrix.ts == 1 && '_TS' || '' }}\php_swow.dll ${{ env.tools_path }}\php\ext\
          "extension_dir=C:\tools\phpdev\php\ext`nzend_extension=opcache`nextension=swow`n" | Out-File ${{ env.tools_path }}\php\php.ini -Encoding ASCII # for no BOM
          php --ri swow
      # shell we move these commands into some bats or composer.json?
      - name: Run extension tests
        shell: cmd
        id: ext-test
        continue-on-error: true
        if: steps.php-inst.outcome == 'success'
        env:
          UNIX_COLOR: "1"
        run: |
          SET NO_INTERACTION=1 && ^
          SET TEST_PHP_EXECUTABLE=C:\tools\phpdev\php\php.exe && ^
          C:\tools\phpdev\php\php.exe ext\tests\runner\run-tests.php ^
            --show-diff ^
            --show-slow 1000 ^
            --set-timeout 30 ^
            --color ^
            ext\tests
      # see notes at cache step
      # TODO: remove this step when upstream fixed the bug
      - name: Remove ini and dll to avoid them being cached
        shell: powershell
        run: |
          Remove-Item ${{ env.tools_path }}\php\ext\php_swow.dll
          Remove-Item ${{ env.tools_path }}\php\php.ini
  uploaddlls:
    name: Upload DLLs
    if: ${{ github.event_name == 'push' }}
    needs:
      - builddlls
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Create Release
        id: create_release
        run: |
          .\.github\workflows\winext\release.ps1 `
            -Repo "${{ github.repository }}" `
            -Token "${{ secrets.GITHUB_TOKEN }}" `
            -TagName "${{ github.ref }}".Split("/")[-1] `
            -prerelease $true
      - name: Fetch artifact
        uses: actions/download-artifact@v2
        with:
          name: ${{ needs.builddlls.outputs.ref }}
          path: .
      - name: Upload all dlls
        shell: powershell
        env:
          UNIX_COLOR: "1"
        run: |
          .\.github\workflows\winext\uploader.ps1 `
            -RelId "${{ steps.create_release.outputs.id }}" `
            -Repo "${{ github.repository }}" `
            -Token "${{ github.token }}"
